export const LABEL = {
  shop: '상호명',
  contact: '대표(개인) 연락처',
  address: '사업장 주소',
  category: '업종 카테고리',
  introduce: '소갯말',
  url: 'URL',
  product: '상품을 입력해 주세요',
  period: '기간',
  startTime: '시작 시간',
  delivery: '배송 예정일',
  price: '가격',
  min: '최소수량',
  max: '최대수량',
  deliveryFee: '배송비 설정',
  freeDelivery: '무료 배송비 설정',
  location: '지역 제한 선택',
  groupBuy: '공동구매 제목',
};
