name: CI Pipeline

on:
  pull_request:
    branches:
      - main
      - dev

permissions:
  contents: read
  pull-requests: write

jobs:
  ci:
    name: CI Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run eslint
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.ACTION_TOKEN }}
          reporter: github-pr-check
          level: error
          eslint_flags: 'src/'

      - name: Test
        run: npm run test:run

      - name: Build
        run: npm run build
