name: CI Pipeline

on:
  pull_request:
    branches:
      - main
      - dev

permissions:
  contents: read
  pull-requests: write

jobs:
  ci:
    name: CI Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4

      - name: 'Install Node'
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Run Stylelint
        uses: reviewdog/action-stylelint@v1
        with:
          reporter: github-pr-check
          stylelint_input: '**/*.{js,jsx,ts,tsx}'

      - name: Run eslint
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.ACTION_TOKEN }}
          reporter: github-pr-check
          level: error
          eslint_flags: 'src/'

      - name: Test
        run: npm run test:run

      - name: Test Coverage Report
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          github-token: ${{ secrets.ACTION_TOKEN }}

      - name: Build
        run: npm run build
